- hosts: all
  user: pi
  vars:
    screenly_systemd_units:
      - X.service
      - matchbox.service
      - screenly-viewer.service
      - screenly-web.service

  tasks:
    - name: Ensure screenly config dir exists
      file: path=/home/pi/.screenly state=directory

    - name: Copy screenly default config
      copy: src=/home/pi/screenly/misc/screenly.conf dest=/home/pi/.screenly/screenly.conf

    - name: Install pip dependencies
      become: yes
      pip: requirements=/home/pi/screenly/requirements.txt

    - name: Create default assets database if not exists
      copy: src=/home/pi/ansible-test/screenly.db dest=/home/pi/.screenly/screenly.db force=no

    - name: Run database migration
      command: python /home/pi/ansible-test/migrate.py
      register: migrate

    - debug: msg="{{ migrate.stdout }}"

    - name: Copy screenly systemd units
      become: yes
      copy: src=/home/pi/ansible-test/systemd/{{ item }} dest=/etc/systemd/system/{{ item }}
      with_items: "{{ screenly_systemd_units }}"

    - name: Enable screenly systemd services
      become: yes
      command: systemctl enable {{ item }} chdir=/etc/systemd/system
      with_items: "{{ screenly_systemd_units }}"